apiVersion: v1
kind: ConfigMap
metadata:
  name: claudecodeui-config
  namespace: claudecodeui
  labels:
    app.kubernetes.io/name: claudecodeui
    app.kubernetes.io/component: config
data:
  NODE_ENV: "production"
  PORT: "3008"
  VITE_PORT: "3009"
  VITE_HOST: "0.0.0.0"
  LOG_LEVEL: "info"
  HEALTH_CHECK_TIMEOUT: "10000"
  SESSION_TIMEOUT: "86400000"
  MAX_FILE_SIZE: "50485760"
  CORS_ORIGIN: "*"
  WS_HEARTBEAT_INTERVAL: "30000"
  
  # Database configuration
  DB_CONNECTION_POOL_MIN: "2"
  DB_CONNECTION_POOL_MAX: "10"
  DB_CONNECTION_TIMEOUT: "60000"
  
  # Security headers
  HSTS_MAX_AGE: "31536000"
  CSP_ENABLED: "true"
  X_FRAME_OPTIONS: "DENY"
  
  # Rate limiting
  RATE_LIMIT_WINDOW: "900000"
  RATE_LIMIT_MAX: "100"
  
  # Monitoring
  METRICS_ENABLED: "true"
  METRICS_PORT: "9090"
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: claudecodeui-nginx-config
  namespace: claudecodeui
  labels:
    app.kubernetes.io/name: claudecodeui
    app.kubernetes.io/component: nginx-config
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log notice;
    pid /var/run/nginx.pid;
    
    events {
        worker_connections 1024;
    }
    
    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
        
        log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';
        
        access_log /var/log/nginx/access.log main;
        
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        client_max_body_size 50M;
        
        # Security headers
        add_header X-Frame-Options DENY always;
        add_header X-Content-Type-Options nosniff always;
        add_header X-XSS-Protection "1; mode=block" always;
        add_header Referrer-Policy "strict-origin-when-cross-origin" always;
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
        
        # Gzip compression
        gzip on;
        gzip_vary on;
        gzip_min_length 1024;
        gzip_proxied any;
        gzip_comp_level 6;
        gzip_types
            application/json
            application/javascript
            application/xml+rss
            application/atom+xml
            image/svg+xml
            text/plain
            text/css
            text/js
            text/xml
            text/javascript;
        
        upstream claudecodeui_backend {
            server claudecodeui-blue-service:3008 max_fails=3 fail_timeout=30s;
            server claudecodeui-green-service:3008 max_fails=3 fail_timeout=30s backup;
            keepalive 32;
        }
        
        # Rate limiting
        limit_req_zone $binary_remote_addr zone=api:10m rate=10r/s;
        limit_req_zone $binary_remote_addr zone=auth:10m rate=1r/s;
        
        server {
            listen 80;
            server_name _;
            return 301 https://$host$request_uri;
        }
        
        server {
            listen 443 ssl http2;
            server_name _;
            
            ssl_certificate /etc/nginx/ssl/tls.crt;
            ssl_certificate_key /etc/nginx/ssl/tls.key;
            ssl_protocols TLSv1.2 TLSv1.3;
            ssl_ciphers ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384;
            ssl_prefer_server_ciphers off;
            ssl_session_cache shared:SSL:10m;
            ssl_session_timeout 10m;
            
            # Health check endpoint
            location /health {
                access_log off;
                proxy_pass http://claudecodeui_backend/health;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_connect_timeout 5s;
                proxy_send_timeout 5s;
                proxy_read_timeout 5s;
            }
            
            # Authentication endpoints with stricter rate limiting
            location ~ ^/(api/auth|login) {
                limit_req zone=auth burst=5 nodelay;
                proxy_pass http://claudecodeui_backend;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_connect_timeout 10s;
                proxy_send_timeout 30s;
                proxy_read_timeout 30s;
            }
            
            # API endpoints
            location /api/ {
                limit_req zone=api burst=20 nodelay;
                proxy_pass http://claudecodeui_backend;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_connect_timeout 10s;
                proxy_send_timeout 60s;
                proxy_read_timeout 60s;
            }
            
            # WebSocket endpoints
            location /ws {
                proxy_pass http://claudecodeui_backend;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_connect_timeout 10s;
                proxy_send_timeout 3600s;
                proxy_read_timeout 3600s;
            }
            
            # Static files with caching
            location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
                proxy_pass http://claudecodeui_backend;
                proxy_set_header Host $host;
                proxy_cache_valid 200 1d;
                expires 1d;
                add_header Cache-Control "public, immutable";
            }
            
            # Default location
            location / {
                proxy_pass http://claudecodeui_backend;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_connect_timeout 10s;
                proxy_send_timeout 30s;
                proxy_read_timeout 30s;
            }
        }
    }