apiVersion: v1
kind: Namespace
metadata:
  name: claudecodeui
  labels:
    name: claudecodeui
    app.kubernetes.io/name: claudecodeui
    app.kubernetes.io/component: namespace
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: claudecodeui-quota
  namespace: claudecodeui
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "20"
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: claudecodeui-limits
  namespace: claudecodeui
spec:
  limits:
  - default:
      cpu: "1"
      memory: "1Gi"
    defaultRequest:
      cpu: "250m"
      memory: "512Mi"
    type: Container
  - default:
      storage: "10Gi"
    type: PersistentVolumeClaim