apiVersion: v1
kind: Secret
metadata:
  name: claudecodeui-secrets
  namespace: claudecodeui
  labels:
    app.kubernetes.io/name: claudecodeui
    app.kubernetes.io/component: secrets
type: Opaque
data:
  # These are base64 encoded placeholder values
  # In production, use proper secret management (e.g., Kubernetes secrets, HashiCorp Vault)
  JWT_SECRET: Y2hhbmdlbWVfaW5fcHJvZHVjdGlvbg==  # changeme_in_production
  SESSION_SECRET: c2VjdXJlX3Nlc3Npb25fc2VjcmV0X2hlcmU=  # secure_session_secret_here
  DB_PASSWORD: ZGJfcGFzc3dvcmRfaGVyZQ==  # db_password_here
  API_KEY: YXBpX2tleV9oZXJl  # api_key_here
  ENCRYPTION_KEY: ZW5jcnlwdGlvbl9rZXlfaGVyZQ==  # encryption_key_here
  
---
apiVersion: v1
kind: Secret
metadata:
  name: claudecodeui-tls
  namespace: claudecodeui
  labels:
    app.kubernetes.io/name: claudecodeui
    app.kubernetes.io/component: tls
type: kubernetes.io/tls
data:
  # Self-signed certificate for development
  # In production, use proper certificates from cert-manager or external CA
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURYVENDQWtXZ0F3SUJBZ0lKQUtOaDNiVDBzWWhUTUEwR0NTcUdTSWIzRFFFQkN3VUFNRVl4Q3pBSkJnTlYKQkFZVEFsVlRNUXN3Q1FZRFZRUUlEQUpEUVRFUE1BMEdBMVVFQnd3R1JtRnNiRzl1TVE4d0RRWURWUVFLREFaVQplWEJwWTJGc01SQXdEZ1lEVlFRRERBZDBaWE4wYVc1bk1CNFhEVEk4TURnd01qRXhNakUzTkZvWERUSTVNRGd3Ck1qRXhNakUzTkZvd1JqRUxNQWtHQTFVRUJoTUNWVk14Q3pBSkJnTlZCQWdNQWtOQk1ROHdEUVlEVlFRSERBWkcKWVd4c2IyNHhEekFOQmdOVkJBb01CbFI1Y0dsamJXdz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRRE5QR2VHVXZPZU5EdnAKNStRcjhzS3RaK2o3Y0w2eXVGRjN1TDJyUVpJZ1B2T2w3aWNIODVyWEtrUUN3ZXpCMVBsWFlpQjFXUUVXWU5jZQpYUzJKRWY4d3dYOXNVdnJ6L1BxZi9lSGJVOVpXQlBGVnVyRlAySU1JYnpKWWZUbEFGeGZpZEc0aWdzNUpPZm94ClBBaFZxdUt5MnNCcDA0cEtYV0RjL0RoSXpEOTI5VFBhSXd1UGZGVFd0bXpuVWpjQ3ZYMmxMQkJUZFJDd05vTHMKU08yNjZXZXdvN0dheFc2OU1CQnlvVlBWSjJNV1VYcWdKMXQveUZaZVFBeFZCbzRYdnY2dXpWZ3RMaEl1TnhWcwp6eHArREVpSFhHOVMzOFhqNXQ1WWwrNnlnVkVncmZrUWFJc1BlWG5yUjZveXpySGpXNkF1VXF1d1Z3VlFMSDE1CkZYRXZJUGFYQWdNQkFBRUNnZ0VBRGxEL3VlZUhVdEhiU0k5ZlE2VHNjQWFNcFBYUUNRS0gzRUQ4TDU5R0NnbisKSlNPWWFWK09VVnNMMXowL2p1VjJrYnB6OXZDR2JJSWJ3TWFJSDBOc0w2K3Z0TG12QUF6WkhvQnVxZmF3VTJHTQpDYU95L0oveTk4VkJ4VzZJRjdSWDJpZy9nSWNRbnpXbUpGa2orcEFDSFI1blRRREdndE5uVGFqYzBRZWVFUnVOCkpLYVpYWXFqOEhPWm1CZWNpdWV1ZGlpQ1RzQTI4WS9acmxoS1lQcWw4UTdQak1BdC8xVU4xd0ZaRkZxeEI5TUIKNkhKWUdrY2RBQVhpeUxNMFY4SzFCR1J6aytMK1NhQ1M4ZEZGTCtaOFRTMndJQU1FR3RuNFVRQW03ckQrMjhybgotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0t

---
apiVersion: v1
kind: Secret
metadata:
  name: claudecodeui-registry
  namespace: claudecodeui
  labels:
    app.kubernetes.io/name: claudecodeui
    app.kubernetes.io/component: registry
type: kubernetes.io/dockerconfigjson
data:
  # Base64 encoded Docker registry credentials
  # Format: {"auths":{"registry.example.com":{"username":"user","password":"pass","auth":"base64(user:pass)"}}}
  .dockerconfigjson: eyJhdXRocyI6e319