apiVersion: v1
kind: Service
metadata:
  name: claudecodeui-blue-service
  namespace: claudecodeui
  labels:
    app.kubernetes.io/name: claudecodeui
    app.kubernetes.io/component: backend
    app.kubernetes.io/version: "blue"
    deployment.claudecodeui.io/slot: blue
spec:
  selector:
    app.kubernetes.io/name: claudecodeui
    app.kubernetes.io/component: backend
    deployment.claudecodeui.io/slot: blue
  ports:
  - name: http
    port: 3008
    targetPort: http
    protocol: TCP
  - name: websocket
    port: 3009
    targetPort: websocket
    protocol: TCP
  type: ClusterIP
  sessionAffinity: None

---
apiVersion: v1
kind: Service
metadata:
  name: claudecodeui-green-service
  namespace: claudecodeui
  labels:
    app.kubernetes.io/name: claudecodeui
    app.kubernetes.io/component: backend
    app.kubernetes.io/version: "green"
    deployment.claudecodeui.io/slot: green
spec:
  selector:
    app.kubernetes.io/name: claudecodeui
    app.kubernetes.io/component: backend
    deployment.claudecodeui.io/slot: green
  ports:
  - name: http
    port: 3008
    targetPort: http
    protocol: TCP
  - name: websocket
    port: 3009
    targetPort: websocket
    protocol: TCP
  type: ClusterIP
  sessionAffinity: None

---
apiVersion: v1
kind: Service
metadata:
  name: claudecodeui-service
  namespace: claudecodeui
  labels:
    app.kubernetes.io/name: claudecodeui
    app.kubernetes.io/component: backend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/health"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "10"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "2"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "3"
spec:
  selector:
    app.kubernetes.io/name: claudecodeui
    app.kubernetes.io/component: backend
    deployment.claudecodeui.io/slot: blue  # Initially points to blue
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: https
    port: 443
    targetPort: http
    protocol: TCP
  - name: websocket
    port: 3009
    targetPort: websocket
    protocol: TCP
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0  # Restrict this in production
  sessionAffinity: None

---
apiVersion: v1
kind: Service
metadata:
  name: claudecodeui-metrics
  namespace: claudecodeui
  labels:
    app.kubernetes.io/name: claudecodeui
    app.kubernetes.io/component: metrics
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app.kubernetes.io/name: claudecodeui
    app.kubernetes.io/component: backend
  ports:
  - name: metrics
    port: 9090
    targetPort: metrics
    protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: claudecodeui-nginx
  namespace: claudecodeui
  labels:
    app.kubernetes.io/name: claudecodeui
    app.kubernetes.io/component: nginx
spec:
  selector:
    app.kubernetes.io/name: claudecodeui
    app.kubernetes.io/component: nginx
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0  # Restrict this in production